### ISSUE TITLE
httpgd plot viewer not working with build by latest `vsce package`

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#1073]
I'm usiing the latest release of vsce (2.7.0) to build the vsix. The httpgd plot viewer no longer works with the following error in console:

```
  ERR isomorphic_ws_1.WebSocket is not a constructor: TypeError: isomorphic_ws_1.WebSocket is not a constructor
    at Object.new_websocket (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/node_modules/httpgd/lib/api.js:56:12)
    at HttpgdConnection.start (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/node_modules/httpgd/lib/connection.js:92:35)
    at HttpgdConnection.open (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/node_modules/httpgd/lib/connection.js:56:14)
    at Httpgd.connect (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/node_modules/httpgd/lib/httpgd.js:47:25)
    at new HttpgdViewer (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/out/plotViewer/index.js:273:23)
    at HttpgdManager.showViewer (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/out/plotViewer/index.js:74:28)
    at updateRequest (/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/out/session.js:709:166)
```

@ManuelHentschel Do you have any idea what might be broken?

**Comment by renkun-ken** [comment]
I inspect the `/home/ken/.vscode-server/extensions/ikuyadeu.r-2.4.0/` folder and there is no `node_modules` in it.

**Comment by renkun-ken** [comment]
Looks like it has nothing to do with vsce. I need to enable webpack and run `vsce package`.
