### ISSUE TITLE
404 error while installing extension

### ISSUE THREAD

**Issue by shriv** [REditorSupport/vscode-R#1111]
**Describe the bug**
VS Code is unable to install the R extension due to a 404 extension. 

**To Reproduce**

1. Go to 'Extensions'
2. Click on 'R' extension to install
```
[2022-05-25 17:08:29.435] [renderer7] [error] ["unknown: Server returned 404","    at Object.n [as asJson] (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:26:96996)","    at V.getEngine (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:789)","    at async V.getLastValidExtensionVersionRecursively (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:967)","    at async V.getCompatibleExtensionByEngine (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:45:8537)","    at async x.checkAndGetCompatibleVersion (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:199551)","    at async x.installFromGallery (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:193412)"]
```

**Expected behavior**
Expected extension to install! 

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.58.1
- R Version: 4.0.3
- vscode-R version: 2.5.0

**Comment by eitsupi** [comment]
Your vscode version is too old.

https://github.com/REditorSupport/vscode-R/blob/4db097d1a099d35eeb4f388ff4b4619f4536f4da/package.json#L28-L30
