### ISSUE TITLE
Help Panel not available in vscode insiders

### ISSUE THREAD

**Issue by TTTPOB** [REditorSupport/vscode-R#1360]
**Describe the bug**
when I open vscode and R extension activated, I see this error pop up at right down corner
![image](https://github.com/REditorSupport/vscode-R/assets/19909103/1530d2bb-06e4-4d9b-9402-236a3b5a2563)

and also when I hit `?something` in attached R terminal, nothing happened

when i trigger the command "R help panel: open help for selection", I got this
![image](https://github.com/REditorSupport/vscode-R/assets/19909103/1093e14a-9dcf-4cff-b54f-4ba392af4fd6)

**To Reproduce**

I think the bug description will do this

**Can you fix this issue by yourself? (We appreciate the help)**

No, i don't know where it came from

**(If applicable) Please attach `setting.json`**
I think this is not related

**Expected behavior**
I can use help

**Environment (please complete the following information):**

- OS: Linux host, windows remote client
- VSCode Version: 1.79.0-insider
- R Version: 4.2.2
- vscode-R version: v2.8.0

**Comment by adamaltmejd** [comment]
For me it only applies to remove host, locally everything works. Also everything works using non-insiders version of VSC.

Tried reinstalling vscode-server on host, and reinstalling the vscode-R extension and disabling all other extensions. Same error. Running the "R Help Panel: Open help for selection" produces the following error:

![Screenshot 2023-05-30 at 14 45 03](https://github.com/REditorSupport/vscode-R/assets/736668/0ec0cd4b-79aa-4299-8bad-83a5a7c803c5)

**Comment by adamaltmejd** [comment]
Maybe found a hint as to why this happens now. Having both a code and a code-insiders windows open at the same time, running "?help" in the code-insiders terminal opens a help window in the code application instead. Is the help panel trying to call code rather than code-insiders when ran from code-insiders?

**Comment by renkun-ken** [comment]
Still not working in the latest release of vscode 1.79.0.

@ManuelHentschel any thoughts?

**Comment by renkun-ken** [comment]
The log in the console:

```
Error while launching R Help: TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/ken/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node_modules/graceful-fs/polyfills.js:313:17)
	at t.isFileSafe (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1436756)
	at p.watchFiles (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1288494)
	at new p (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1288139)
	at t.makePreviewerList (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1287730)
	at new _ (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1299168)
	at Object.t.initializeHelp (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1297473)
	at async t.activate (/home/ken/.vscode-server/extensions/reditorsupport.r-2.8.0/dist/extension.js:2:1284339)
	at async b.n (/home/ken/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:98:6644)
	at async b.m (/home/ken/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:98:6607)
	at async b.l (/home/ken/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:98:6064)
```

**Comment by renkun-ken** [comment]
Looks like `fs.statSync(path, { throwIfNoEntry: false })` still raise exceptions?

**Comment by as00419** [comment]
same problem as you. Was there a request.log file in ~/.vscode-R? 
Every time when i typed ?xx in radian, this file updated, like:

{"time":"2023-06-09 16:36:43",
"pid":27240,
"wd":"/current/work/directory",
"command":"help",
"requestPath":"/library/base/html/mean.html",
"viewer":"Two"}

and the requestPath was invalid.  will this help?
