### ISSUE TITLE
Issue launching extension ("spawn EINVAL")

### ISSUE THREAD

**Issue by b-rhodes** [REditorSupport/vscode-R#1549]
**Describe the bug**
Whenever I open VSCode, I get a little panel popping up saying "Help panel unavailable", and then when I look at the extension runtime status, it has:

### Uncaught Errors (1)
spawn EINVAL

**To Reproduce**

1. Open VSCode
2. Click on 'extensions'
3. Scroll down to 'R'
4. Click on 'FEATURES' tab
5. Click on 'Runtime Status'
6. See the error

**Can you fix this issue by yourself? (We appreciate the help)**

No

```jsonc
    "r.plot.useHttpgd": true,
    "r.libPaths": [
        "C:\\Users\\<username>\\.vscode-R\\renv\\library\\R-4.3\\x86_64-w64-mingw32",
        "C:\\Users\\<username>\\.vscode-R\\renv\\library\\R-4.4\\x86_64-w64-mingw32",
        "C:\\Users\\<username>\\AppData\\Local\\R\\win-library\\4.3",
        "C:\\Users\\<username>\\AppData\\Local\\R\\win-library\\4.4"
    ],
    "r.lsp.debug": true,
    "r.lsp.diagnostics": true,
    "r.rpath.windows":"C:\\Program Files\\R\\bin\\R.bat",
    "r.rterm.option": [
        "--no-save"
    ],
    "r.rterm.windows": "C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\Scripts\\radian.exe",
    "r.useRenvLibPath": true,
    "shiny.r.port": 8080
```

**Environment (please complete the following information):**

- OS: Windows 11
- VSCode Version: 1.92.1
- R Version: 4.4.0
- vscode-R version: 2.8.4

**Additional context**
I'm using Rig to allow for changing R versions

**Comment by b-rhodes** [comment]
I found some error in the extension host output:
```
2024-08-20 09:15:38.320 [error] Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at R (c:\Users\<username>\.vscode\extensions\reditorsupport.r-2.8.4\dist\extension.js:2:454372)
	at t.LanguageService.spawnServer (c:\Users\<username>\.vscode\extensions\reditorsupport.r-2.8.4\dist\extension.js:2:347396)
	at Server.<anonymous> (c:\Users\<username>\.vscode\extensions\reditorsupport.r-2.8.4\dist\extension.js:2:349708)
	at Object.onceWrapper (node:events:633:28)
	at Server.emit (node:events:519:28)
	at emitListeningNT (node:net:1932:10)
	at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Comment by b-rhodes** [comment]
still haven't managed to find a fix for this, so I've just been putting up with it or swapping to Positron when I desperately need the features.

**Comment by b-rhodes** [comment]
I've stopped having this issue, but I'm not sure what fixed it. I reinstalled VSCode and R several times.

**Comment by ThomasSoeiro** [comment]
@Fred-Wu @grantmcdermott @eitsupi Close as not reproducible?

I can't reproduce with `vscode-R 3.0.0-rc.0`.

VSCode about:

```
Version: 1.138.0
Commit: 7debcd0e2acdea1c52de81bf9ee1620444407dda
Date: 2026-09-15T07:24:32Z
Electron: 42.10.0
ElectronBuildId: 15109253
Chromium: 148.0.7778.280
Node.js: 24.18.1
V8: 14.8.178.38-electron.0
@github/copilot: 1.0.84-4
@github/copilot-sdk: 1.0.13
OS: Linux x64 6.17.10-100.fc41.x86_64
```

`sessionInfo()`:

```
R version 4.4.3 (2025-02-28)
Platform: x86_64-redhat-linux-gnu
Running under: Fedora Linux 41 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Paris
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.3
```

**Comment by eitsupi** [comment]
This is outdated, so I'm closing it.
Please let me know if you continue to experience problems.
