### ISSUE TITLE
Minimum VSCode Version for `vscode-r` v2.0.0

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/vscode-R#704]
I am installing vscode-r from openvsx in a centralized installation which currently makes use of [code-server]() v 3.10.2 which again ships vscode 1.56.1.

While vscode-R v1.6.6 can be installed, I get an error for v2.0.0. Do you know what the minimum vscode version required is for v2.0.0? 

This is mainly for me knowing how long I need to pin the old version to prevent the installation failures.

```bash
VSCODE_R_VERSION=1.6.6
curl -sL https://open-vsx.org/api/Ikuyadeu/r/${VSCODE_R_VERSION}/file/Ikuyadeu.r-${VSCODE_R_VERSION}.vsix -o Ikuyadeu.r-${VSCODE_R_VERSION}.vsix && /usr/bin/code-server --extensions-dir /usr/lib/code-server/lib/vscode/extensions --install-extension Ikuyadeu.r-${VSCODE_R_VERSION}.vsix && rm Ikuyadeu.r-${VSCODE_R_VERSION}.vsix
Installing extensions...
Extension 'Ikuyadeu.r-1.6.6.vsix' was successfully installed.

VSCODE_R_VERSION=2.0.0
curl -sL https://open-vsx.org/api/Ikuyadeu/r/${VSCODE_R_VERSION}/file/Ikuyadeu.r-${VSCODE_R_VERSION}.vsix -o Ikuyadeu.r-${VSCODE_R_VERSION}.vsix   && /usr/bin/code-server --extensions-dir /usr/lib/code-server/lib/vscode/extensions --install-extension Ikuyadeu.r-${VSCODE_R_VERSION}.vsix   && rm Ikuyadeu.r-${VSCODE_R_VERSION}.vsix
Installing extensions...
Unable to install extension 'ikuyadeu.r' as it is not compatible with VS Code '1.56.1'.
[2021-07-13T15:59:50.187Z] error vscode Failed Installing Extensions: file:///Ikuyadeu.r-2.0.0.vsix
[2021-07-13T15:59:50.188Z] error vscode Error: Failed Installing Extensions: file:///Ikuyadeu.r-2.0.0.vsix
    at O.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:90861
    at async M (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
    at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
```

**Comment by renkun-ken** [comment]
[Here](https://github.com/REditorSupport/vscode-R/blob/master/package.json#L29) we require a minimum version `1.57.0`. I'm not sure how we determined this, but do we really need it? Or should we set it to the earliest version we really rely on?

**Comment by Ikuyadeu** [comment]
I set it to use the latest VS Code at that time with each release.
This is due to frequent API security and performance improvements.

Also, users can use the old vscode-r version if they want.
In my opinion, I want to prioritize standard VS Code over vscode-like things like code-server and eclipse.

**Comment by renkun-ken** [comment]
Does it make more sense to set to the previous 3 or 4 version as the minimum version in each release? Some user might not be timely upgrading to the latest release due to many causes, e.g. in a corporate environment where installation of external software is controlled, having some blocking issues introduced in the newer released. I think these users perfectly deserve to use the latest vscode-R which does not really have a hard dependency on the most recent releases.

**Comment by renkun-ken** [comment]
I notice that both [vscode-python](https://github.com/microsoft/vscode-python/blob/main/package.json#L40) and [vscode-julia](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L9), both require `1.57.0`. Looks like it is a quite standard practice. Does this engine version affect the performance of behavior of extension?

**Comment by Ikuyadeu** [comment]
Thank you for your survey.

If some users have network limitation, they also can not install the previous 3 or 4 version, and the latest vscode-r.
I think, using the latest version of the software is a security standard and not a special circumstance.

If **latest** vscode-r is not so important, Python, julia, and we distribute old version on the [GitHub release](https://github.com/REditorSupport/vscode-R/releases).

**Comment by pat-s** [comment]
In my case, I am trying to automate things to simplify the installation for a corporate environment.

RStudio Workbench and its VSCode Integration require the use of `code-server` and it will be great if at least the last version of this project could be supported by `vscode-r` **if** there are not important reasons to have a higher requirement.

Otherwise I always need to pin an old version and stop the automation (i.e. scraping the latest `vscode-r` version automatically) and possibly enable it again a few weeks later.

I see this pattern of enabling/disabling potentially coming up more often if `vscode-r` bumps is minimum quite early after release when `code-server` has not yet catched up.

Of course this is not really an issue of this project here and more a convenience devops thing of mine. Hence I understand if you decide differently but maybe the minimum version could be relaxed in the light of the context just described if it does not hurt anyone else :)

You could also potentially implement a heuristic to always have the latest `code-server` as the minimum version (for compatibility).

Thanks for your work!

**Comment by ManuelHentschel** [comment]
> 
> 
> [Here](https://github.com/REditorSupport/vscode-R/blob/master/package.json#L29) we require a minimum version `1.57.0`. I'm not sure how we determined this, but do we really need it? Or should we set it to the earliest version we really rely on? @Ikuyadeu @ManuelHentschel

[Here](https://github.com/REditorSupport/vscode-R/blob/master/package.json#L1396) is another place we rely on `1.57.0`, and indirectly anywhere in the code, where we use functions that are present for v1.57 but not the older ones.

Also, sometimes the contributions declared in package.json depend on a certain version of vscode. E.g. the [`"editor/title/run"`](https://github.com/REditorSupport/vscode-R/blob/master/package.json#L863) menu was introduced somewhat recently and produces a warning in older versions of vscode.

With this in mind, we should probably bump the vscode version only if we actually implement a feature or use an API that is not present in older vscode versions. After all it's a minimum version, not a "recommended version".

**Comment by renkun-ken** [comment]
From the `devDependencies` in `package.json`, [vscode-python](https://github.com/microsoft/vscode-python/blob/main/package.json#L2174) depends on `~1.53.0` while [vscode-julia](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L1227) on `^1.57.0`. I'm not quite sure about how things work out given the inconsistencies here.

**Comment by ManuelHentschel** [comment]
> 
> 
> From the `devDependencies` in `package.json`, [vscode-python](https://github.com/microsoft/vscode-python/blob/main/package.json#L2174) depends on `~1.53.0` while [vscode-julia](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L1227) on `^1.57.0`. I'm not quite sure about how things work out given the inconsistencies here.

I think the engine "vscode" is backwards compatible, so vsce doesn't mind working with an older `@types/vscode` (and the `~` vs `^` is only relevant for npm/yarn to select the correct version of `@types/vscode`) and both these extensions specify `vscode: ^1.57.0` as engine. The other way around gives an error, though.
