### ISSUE TITLE
chooseTerminal issue

### ISSUE THREAD

**Issue by sunnyjones5** [REditorSupport/vscode-R#899]
**Describe the bug**
My vscode has been buggy since yesterday afternoon and occasionally not letting me use Command+Enter to send code to the terminal. Additionally plots have no longer been appearing in a separate window (I use httpgd). I went to restart the application an received and error message saying "Error identifying terminal" and was told to paste the [chooseTerminal] error message here. This is what it says:

`[chooseTerminal] A. There are 2 terminals: Terminal 0: bash Terminal 1: R B. There are 2 terminals: Terminal 0: bash Terminal 1: R C. There are 2 terminals: Terminal 0: bash Terminal 1: R 
`
Followed by this, but I am not sure if this is also important.

```
ERR Bad progress location: rHelpPages: Error: Bad progress location: rHelpPages
    at s.withProgress (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1734:1049)
    at C.$startProgress (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1518:29160)
    at f._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:13095)
    at f._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:12779)
    at f._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:11441)
    at f._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:10119)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1525:8215
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:16680)
    at d._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:21950)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:18828
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at m.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:14041)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:85:13389
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:40536
    at l.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:69:1712)
    at FileReader._fileReader.onload (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:610:39096)
```

This error also appeared as well

```
 ERR [Extension Host] (node:4675) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:4675) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
E @ console.ts:137
```

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.62.3
- R Version: 4.1.2
- vscode-R version: 2.3.4

**Additional context**

**Comment by renkun-ken** [comment]
Does it happen if you rollback to vscode-R 2.3.3?

**Comment by greadsk** [comment]
> Does it happen if you rollback to vscode-R 2.3.3?

I tried, can not be solved.(I also get the same problem)

**Comment by sunnyjones5** [comment]
I originally marked this as closed because after restarting it again it seemed to go away for a bit but then it started happening again. Any other ides for what I should do?

**Comment by sunnyjones5** [comment]
I have also noticed that VScode now uses almost all my memory even when I am only doing basic things and this is the only extension I have installed (it's currently using ~ 7GB out of my 8GB)

**Comment by greadsk** [comment]
这是来自QQ邮箱的自动回复邮件。      您好，您的邮件我收到啦！

**Comment by renkun-ken** [comment]
Do you open multiple terminals in VS Code?

>I have also noticed that VScode now uses almost all my memory even when I am only doing basic things and this is the only extension I have installed (it's currently using ~ 7GB out of my 8GB)

Would you like to see what processes are exhausting your memory using monitor or htop?

**Comment by sunnyjones5** [comment]
I typically only use 1 terminal. This afternoon I switched back to  vscode-R 2.3.3 because I noticed the timing of the newest release coincided with when I started to have issues and it has been working much better now, so it must have something to do with whatever is in the new code. I have been using activity monitor to view the memory, that's how I noticed the issue.

**Comment by ElianHugh** [comment]
I think this has something to do with the new 'persistent sessions' setting for terminals. Turning it off resolved this one for me

**Comment by andrasbalogh** [comment]
I had some very old workplace open in the background for some reason. I think closing the workplace solved the issue for me.

**Comment by sunnyjones5** [comment]
Just following up on this, is there a plan to address this? Whenever I update I still run into this issue and have to revert back to 2.3.3.

**Comment by greadsk** [comment]
这是来自QQ邮箱的自动回复邮件。      您好，您的邮件我收到啦！

**Comment by renkun-ken** [comment]
@sunnyjones5 Did you try turnning off `terminal.integrated.enablePersistentSessions`?

**Comment by sunnyjones5** [comment]
Yes but it still run into the same issue

**Comment by fciotti** [comment]
I had the same issue. It went away by turning off `terminal.integrated.enablePersistentSessions`. Loosing a useful feature tho.

**Comment by sunnyjones5** [comment]
Following up on this, I notice that this issue arises whenever I begin generating a number of plots (using httpgd as recommended), and it causes VScode to either slow down or crash entirely.

**Comment by renkun-ken** [comment]
A note here: https://code.visualstudio.com/updates/v1_64#_disable-terminal-persistence should be useful in the future.

**Comment by oduilln** [comment]
> Following up on this, I notice that this issue arises whenever I begin generating a number of plots (using httpgd as recommended), and it causes VScode to either slow down or crash entirely.

I am having an identical issue. Did you ever find a resolution to this?

**Comment by greadsk** [comment]
这是来自QQ邮箱的自动回复邮件。      您好，您的邮件我收到啦！

**Comment by sunnyjones5** [comment]
Nope. I disabled terminal persistence and it didn't help. For a while I kept using the other version of vscode-R before the update that introduced this error but now if I know I am going to be generating more than just a few plots I save them directly as pngs and view the output files.

**Comment by greadsk** [comment]
这是来自QQ邮箱的自动回复邮件。      您好，您的邮件我收到啦！

**Comment by greadsk** [comment]
这是来自QQ邮箱的自动回复邮件。      您好，您的邮件我收到啦！
